# Generated by Django 5.1.4 on 2024-12-22 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sgxnifty',
            name='time',
        ),
        migrations.AddField(
            model_name='sgxnifty',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
